dagrs-dev/dagrs

- Cargo.toml
- 修复一个由于deno_core包版本太低可能导致其他依赖包的依赖关系不满足的问题
> fix:deno_core包可能导致once cell依赖的版本问题

- src/task/mod.rs
Due to storage of Task in a Box in an Arc, the task can be declared Send/Sync. https://rust-lang.github.io/rust-clippy/master/index.html#/arc_with_non_send_sync
> fix: make the trait Task Send/Sync

- README.md
- examples/compute_dag.rs
- examples/custom_log.rs
- examples/custom_parser.rs
- examples/custom_task.rs
- examples/engine.rs
- examples/impl_action.rs
- examples/use_macro.rs
- examples/yaml_dag.rs
- src/main.rs
- src/utils/log.rs
- tests/dag_job_test.rs
This changes the `init_logger` and `init_custom_logger` to return an error when the logger is already initialized instead of printing to the stdout.
This has multiple benefits:
- The error can be handled properly
- The error can be ignored if the user doesn't care about this particular error
> fix: return an error for Logger initialization instead of printing

- src/engine/dag.rs
It is very useful to be able to access the output of every task in a job not just the last one.
Created a method get_results similar to get_result to return a hashmap of all the task ids and their outputs.
> add a method to get the output from all tasks

- Cargo.toml
- src/utils/default_logger.rs
- src/utils/log.rs
- src/utils/mod.rs
This moves the default logger implementation to a separate file. The common methods remain in the log module, but they can become no-op when the `logger` feature is disabled via `default-features=false`
> feat: allow disabling the logger via a feature

- .gitignore
- .vscode/settings.json
- README.md
- dagrs_core/Cargo.toml
- dagrs_core/src/engine/dag.rs
- dagrs_core/src/parser/mod.rs
- dagrs_core/src/parser/yaml_parser.rs
- dagrs_core/src/task/default_task.rs
- dagrs_core/src/task/yaml_task.rs
- dagrs_derive/Cargo.toml
- examples/custom_parser.rs
- examples/custom_task.rs
- examples/dependencies.rs
- examples/engine.rs
- tests/dag_job_test.rs
This allows creating actions with any lifetime and not just `'static`. This makes it easier to create generic actions.
> feat: relax the lifetime constraints on the actions

- .vscode/settings.json
- Cargo.toml
- README.md
- examples/compute_dag.rs
- examples/custom_parser_and_task.rs
- examples/dependencies.rs
- src/engine/mod.rs
- src/utils/parser.rs
- src/yaml/mod.rs
- tests/dag_job_test.rs
This implements `thiserror::Error` for all error types of the package. This has many benefits such as the possibility to use `?`, standard conversion to/from other error types, and simplification of error handling.
> feat: implement Error trait for all error types

- examples/compute_dag.rs
- src/engine/dag.rs
- src/task/action.rs
- src/task/default_task.rs
- src/utils/default_logger.rs
- src/utils/log.rs
- This adds the `_dyn` variation of the methods that allows passing dynamic tasks/actions 
- Relaxes the `'static` lifetime requirements
It reimplements #36 for #37
> feat: support dynamic action/tasks + relax the lifetime constraints

- src/task/cmd.rs
- src/task/mod.rs
- src/task/state.rs
For your consideration as this pull request also contains breaking changes.
This request allows for the capture of stdout and stderr regardless of whether a task completes successfully.  It also allows for the capturing of the OS's exit code in the case of a failure.
Thanks, Kris.
> Stdout stderr to vec plus error exit codes

- src/engine/dag.rs
- src/yaml/yaml_parser.rs
Also eliminates an unused import warning caused by a previous commit.
> Remove some unwraps

- benches/compute_dag_bench.rs
- examples/compute_dag.rs
- examples/custom_log.rs
- examples/custom_parser_and_task.rs
- examples/engine.rs
- examples/yaml_dag.rs
- src/bin/dagrs.rs
- src/engine/dag.rs
- src/engine/mod.rs
- src/lib.rs
- src/utils/mod.rs
- src/utils/parser.rs
- src/yaml/mod.rs
- src/yaml/yaml_parser.rs
- tests/dag_job_test.rs
- tests/yaml_parser_test.rs
This PR introduces error propagation. This is an improvement because we are now able to see, e.g.,  errors of individual tasks during the DAG construction.
> Use error propagation

- src/engine/dag.rs
This PR adds a reset function to the API.
With this reset function we can construct a DAG once and execute it multiple times. This has been working fairly well for me for the past weeks during active testing.
> Add graph reset function

- src/engine/dag.rs
- src/task/cmd.rs
- src/task/state.rs
task/state.rs:
- New method to the full output
engine/dag.rs:
- Set the output on task errors
- New method to get the full output
task/cmd.rs:
- Get the status code regardless of result
- Output::new already wraps the type into Content, but error_with_exit_code does not
> Add ability to retrieve full output of tasks and some cmd fixes

- .github/workflows/base.yml
- Cargo.toml
- src/connection/in_channel.rs
- src/connection/information_packet.rs
- src/connection/mod.rs
- src/connection/out_channel.rs
- src/graph/mod.rs
- src/graph/node.rs
- src/lib.rs
- Channel definition and unified implementaion of send & recv. #72 
- Def of information package (use `Content` in the old ver.). #71
> Wrap tokio channels & Information Package Def

- .github/workflows/base.yml
- Cargo.toml
- src/connection/in_channel.rs
- src/connection/mod.rs
- src/connection/out_channel.rs
- src/graph/mod.rs
- src/graph/node.rs
- src/lib.rs
- src/node/action.rs
- src/node/default_node.rs
- src/node/id_allocate.rs
- src/node/mod.rs
- src/node/node.rs
- src/utils/env.rs
- src/utils/mod.rs
- src/utils/output.rs
This PR encapsulates FBP processes by trait `Node` + `Action`.
We use `NodeTable` to allocate node ids so that we can also record the mapping from node name to node id.
related issues: #71 
Based on the discussion in #75, we changed the visibility of `InChannel` and `OutChannel`, and modified the logic of throwing RecvErr exceptions.
> Encapsulation of processes and information packets

- src/connection/in_channel.rs
- src/connection/out_channel.rs
- src/graph/graph.rs
- src/graph/mod.rs
- src/lib.rs
- src/utils/execstate.rs
- src/utils/mod.rs
related issues: https://github.com/dagrs-dev/dagrs/issues/74
- Remove field rely_graph：Since node provides input and output channels, graph only needs to connect the input and output channels of different nodes according to the dependency relationship
- Automatically create channels and assign corresponding senders and receivers to the nodes when building the graph：When the dependencies are a-> B, C, D one-to-many, a broadcast channel needs to be created. The output channel of A is the channel sender, and the input channel of BCD is the receiver；When the dependency is a one-to-one situation like a-> B, an MPSC channel needs to be created, with A's output channel being the channel sender and B's input channel being the receiver
-  Modify the logic of error-handling: If one node fails, the …
> FBP Asynchronous feature：Provide a struct Graph, replacing Dag in the old version.

- Cargo.toml
- derive/src/lib.rs
- derive/src/relay.rs
- examples/auto_relay.rs
- src/graph/graph.rs
- src/lib.rs
The auto_graph macro is used in DAGRS to automate the generation of corresponding graph structures for provided dependencies, where nodes can be any custom nodes that implement the node trait, and only the dependencies between nodes need to be provided
Firstly, it is necessary to define the nodes that have implemented the node trait
```rust
let s = MyNode {
id: node_table.alloc_id_for(&node_name),
name: node_name.clone(),
input_channels: InChannels::default(),
output_channels: OutChannels::default(),
action: Box::new(EmptyAction),
};
let a = MyNode {
id: node_table.alloc_id_for(&node_name),
name: node_name.clone(),
input_channels: InChannels::default(),
output_channels: OutChannels::default(),
action: Box::new(EmptyAction),
};
let b = MyNode {
id: node_table.alloc_id_for(&node_name), …
```
> Parser: auto_graph macro

- Cargo.toml
- derive/src/auto_node.rs
- derive/src/relay.rs
- examples/auto_node.rs
- examples/auto_relay.rs
- examples/compute_dag.rs
- examples/custom_node.rs
- examples/hello_dagrs.rs
- src/connection/in_channel.rs
- src/connection/out_channel.rs
- src/graph/graph.rs
- src/lib.rs
- src/node/default_node.rs
- src/node/node.rs
- src/utils/execstate.rs
- src/utils/output.rs
- hello_dagrs: creates a `DefaultNode` that returns with "Hello Dagrs", then create a new `Graph` with this node and run.
- custom_node: creates a custom implementation of `Node`, then create a new [`Graph`] with this node and run.
- compute_dag:  Only use Dag, execute a job that computes:
```
↱----------↴
B -→ E --→ G
↗    ↗     ↗
A --→ C    /
↘    ↘  /
D -→ F
```
When I wrote the example "compute_dag", I found that the execution of nodes were not asynchronous at all.
@A-Mavericks  and I fixed this issue. 
We adjusted the method `Node::run` to be asynchronous and modify the implementation of scheduling nodes in Graph.
> examples & fix of async graph run

- examples/conditional_node.rs
- examples/dagrs-sklearn/examples/sklearn.rs
- src/graph/graph.rs
- src/node/conditional_node.rs
- src/node/mod.rs
- src/node/node.rs
- src/utils/output.rs
This PR introduces a new `ConditionalNode` type and updates the graph execution logic to support conditional workflows.
- Added `ConditionalNode`: A specialized node type that can control the execution flow based on custom conditions
- Implemented block-based execution in the graph, where nodes are grouped into blocks separated by conditional nodes
- Added support for early termination of subsequent blocks when a condition fails
- Modified `Graph::check_loop()` to not only detect cycles but also divide nodes into execution blocks
- Updated `Graph::run()` to execute nodes block by block
- Added ability to abort remaining blocks when a condition evaluates to false
Added a example (`examples/conditional_node.rs`) demonstrating:
- A DAG with conditional branching
- Block-based execution flow …
> Conditional Node

- dagrs-derive/src/auto_node.rs
- examples/compute_dag.rs
- examples/conditional_node.rs
- examples/dagrs-sklearn/examples/sklearn.rs
- examples/dagrs-sklearn/src/command_action.rs
- examples/hello_dagrs.rs
- examples/loop_dag.rs
- src/connection/in_channel.rs
- src/connection/out_channel.rs
- src/graph/abstract_graph.rs
- src/graph/graph.rs
- src/graph/loop_subgraph.rs
- src/graph/mod.rs
- src/node/action.rs
- src/node/default_node.rs
- src/node/node.rs
1. Implemented `LoopSubgraph` structure to support cyclic execution patterns in DAG. Loop checking is moved to `abstract_graph`.
The `LoopSubgraph` is a special node type that folds a group of nodes that need to be executed in a loop. It implements the `Node` trait but delegates the actual execution to its parent graph, allowing for controlled cyclic execution patterns while maintaining the DAG structure at the macro level.
The `loop_dag.rs` example demonstrates a use case with three nodes:
```
//! IN
//! |          +----------+
//! |          ↓          |
//! +-----> INTER ----> PROC
//！ A loop dag where K is the starter ("kicker") process, that emits a single packet containing a blank,
//! (imagine) INTER controls a screen. In this figure, INTER receives some data from PROC, displays it …
```
> Support Loop Subgraph Structure and Improve Channel Mutability

- src/node/node.rs
Add Ord and PartialOrd traits to NodeId to enable sorting.  This is useful for iterating through the results in order.
> Add Ord and PartialOrd traits to NodeId to enable sorting

- examples/typed_action.rs
- src/connection/in_channel.rs
- src/connection/information_packet.rs
- src/connection/out_channel.rs
- src/node/mod.rs
- src/node/node.rs
- src/node/typed_action.rs
This PR introduces `TypedAction` and typed channels (`TypedInChannels` and `TypedOutChannels`) to provide fixed-type communication between nodes in the DAG. This enhancement ensures compile-time type checking for data flow between nodes.
The original design of adding typed channels directly to the graph structure faced challenges due to Rust's type system constraints. When using generic type parameters for channels, it becomes difficult to maintain type safety while keeping the graph structure flexible and dynamic. This is because:
1. The graph needs to handle nodes with different input/output types
2. Generic type parameters would need to be propagated through the entire graph structure
3. Type erasure would be necessary at some point, potentially compromising type safety
To address …
> Typed Channels

- Cargo.toml
- examples/recv_any_example.rs
- examples/typed_action.rs
- src/connection/in_channel.rs
- src/connection/out_channel.rs
This PR introduces several improvements to the information packet (IP) management in Dagrs:
Added `recv_any` method to receive data from any available channel without specifying the sender's ID, which returns a tuple of `(sender_id, content)` to identify the message source.
Added `get_receiver_ids` method to query available receiver nodes.
`recv_any_example.rs` demonstrates how to use the `recv_any` method of `InChannels` to receive data from any available channel.
This example creates a graph with two senders and one receiver:
- A normal sender that sends messages immediately
- A slow sender that delays 500ms before sending messages
- A receiver that uses `recv_any` to receive messages from either sender
```
/// An action that sends a message to its output channel
#[derive(Default)]
pub …
```
> Better IP management
